"""add field default_source to user

Revision ID: 14bb10463375
Revises: b703d56ecfe5
Create Date: 2026-04-21 02:23:25.886687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14bb10463375'
down_revision: Union[str, Sequence[str], None] = 'b703d56ecfe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_news_source', sa.String(), server_default='kommersant', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'default_news_source')
    # ### end Alembic commands ###
