"""add news_on_page field to user

Revision ID: d053a9faa778
Revises: 14bb10463375
Create Date: 2026-04-21 12:05:09.357957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd053a9faa778'
down_revision: Union[str, Sequence[str], None] = '14bb10463375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('news_on_page', sa.Integer(), server_default='20', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'news_on_page')
    # ### end Alembic commands ###
